In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\prajwal kutwal\Downloads\amazon_sales_dataset.csv")

In [5]:
df.head()

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
0,1,2022-04-13,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52
1,2,2023-03-12,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28
3,4,2022-04-17,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64
4,5,2022-03-13,1717,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  object
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  object
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  object
 8   payment_method    50000 non-null  object
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 5.0+ MB

In [7]:
df.isnull().sum()

order_id            0
order_date          0
product_id          0
product_category    0
price               0
discount_percent    0
quantity_sold       0
customer_region     0
payment_method      0
rating              0
review_count        0
discounted_price    0
total_revenue       0
dtype: int64

In [15]:
import pandas as pd
df2 = pd.read_csv(r"C:\Users\prajwal kutwal\Downloads\flipkard.csv")

In [16]:
df2.head()

,product_id,product_name,category,brand,seller,seller_city,price,discount_percent,final_price,rating,...,weight_g,warranty_months,color,size,return_policy_days,is_returnable,payment_modes,shipping_weight_g,product_score,seller_rating
0,FKP0000001,Adidas Ultra 664,Toys,Adidas,MegaStore,Hyderabad,35547.34,15,30215.24,1.9,...,3038.23,36,Green,XL,30,True,"COD,CARD",3483.592454,6.78,3.28
1,FKP0000002,LG Series 124,Fashion,LG,ValueKart,Mumbai,30693.79,10,27624.41,3.2,...,1921.82,0,Grey,One Size,7,True,"UPI,CARD",2091.473835,50.78,3.42
2,FKP0000003,Redmi Model 35,Beauty,Redmi,SmartDeals,Ahmedabad,51214.50,40,30728.70,4.4,...,1143.49,12,Black,M,0,False,"COD,UPI,CARD",1242.770494,4.24,4.23
3,FKP0000004,Sony Edition 769,Toys,Sony,UrbanRetails,Delhi,33168.49,30,23217.94,2.8,...,3644.81,24,Black,L,0,False,"CARD,Wallet",3891.222716,1.38,3.45
4,FKP0000005,Boat Prime 291,Home & Kitchen,Boat,RetailHub,Pune,14181.34,0,14181.34,3.7,...,310.33,0,Blue,NaN,30,True,"CARD,Wallet",386.061014,79.27,4.90

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          80000 non-null  object
 1   product_name        80000 non-null  object
 2   category            80000 non-null  object
 3   brand               80000 non-null  object
 4   seller              80000 non-null  object
 5   seller_city         80000 non-null  object
 6   price               80000 non-null  float64
 7   discount_percent    80000 non-null  int64
 8   final_price         80000 non-null  float64
 9   rating              80000 non-null  float64
 10  review_count        80000 non-null  int64
 11  stock_available     80000 non-null  int64
 12  units_sold          80000 non-null  int64
 13  listing_date        80000 non-null  object
 14  delivery_days       80000 non-null  int64
 15  weight_g            80000 non-null  float64
 16  warranty_months     80000 non-null  int64
 17  color               80000 non-null  object
 18  size                66516 non-null  object
 19  return_policy_days  80000 non-null  int64
 20  is_returnable       80000 non-null  bool
 21  payment_modes       80000 non-null  object
 22  shipping_weight_g   80000 non-null  float64
 23  product_score       80000 non-null  float64
 24  seller_rating       80000 non-null  float64
dtypes: bool(1), float64(7), int64(7), object(10)
memory usage: 14.7+ MB

In [18]:
df2.isnull().sum()

product_id                0
product_name              0
category                  0
brand                     0
seller                    0
seller_city               0
price                     0
discount_percent          0
final_price               0
rating                    0
review_count              0
stock_available           0
units_sold                0
listing_date              0
delivery_days             0
weight_g                  0
warranty_months           0
color                     0
size                  13484
return_policy_days        0
is_returnable             0
payment_modes             0
shipping_weight_g         0
product_score             0
seller_rating             0
dtype: int64

In [20]:
df2['size'].isnull().sum()

np.int64(13484)

In [21]:
df2['size'] =df2['size'].fillna('Not Applicable')

In [23]:
df2['size'].isnull().sum()

np.int64(0)

In [24]:
df2['size'] = df2['size'].fillna('Not Applicable')
df2.isnull().sum()

product_id            0
product_name          0
category              0
brand                 0
seller                0
seller_city           0
price                 0
discount_percent      0
final_price           0
rating                0
review_count          0
stock_available       0
units_sold            0
listing_date          0
delivery_days         0
weight_g              0
warranty_months       0
color                 0
size                  0
return_policy_days    0
is_returnable         0
payment_modes         0
shipping_weight_g     0
product_score         0
seller_rating         0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df2.duplicated().sum()

np.int64(0)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  object
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  object
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  object
 8   payment_method    50000 non-null  object
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 5.0+ MB

In [29]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  datetime64[ns]
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  object
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  object
 8   payment_method    50000 non-null  object
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(5), object(3)
memory usage: 5.0+ MB

In [31]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          80000 non-null  object
 1   product_name        80000 non-null  object
 2   category            80000 non-null  object
 3   brand               80000 non-null  object
 4   seller              80000 non-null  object
 5   seller_city         80000 non-null  object
 6   price               80000 non-null  float64
 7   discount_percent    80000 non-null  int64
 8   final_price         80000 non-null  float64
 9   rating              80000 non-null  float64
 10  review_count        80000 non-null  int64
 11  stock_available     80000 non-null  int64
 12  units_sold          80000 non-null  int64
 13  listing_date        80000 non-null  object
 14  delivery_days       80000 non-null  int64
 15  weight_g            80000 non-null  float64
 16  warranty_months     80000 non-null  int64
 17  color               80000 non-null  object
 18  size                80000 non-null  object
 19  return_policy_days  80000 non-null  int64
 20  is_returnable       80000 non-null  bool
 21  payment_modes       80000 non-null  object
 22  shipping_weight_g   80000 non-null  float64
 23  product_score       80000 non-null  float64
 24  seller_rating       80000 non-null  float64
dtypes: bool(1), float64(7), int64(7), object(10)
memory usage: 14.7+ MB

In [32]:
df2['listing_date'] = pd.to_datetime(df2['listing_date'])

In [33]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          80000 non-null  object
 1   product_name        80000 non-null  object
 2   category            80000 non-null  object
 3   brand               80000 non-null  object
 4   seller              80000 non-null  object
 5   seller_city         80000 non-null  object
 6   price               80000 non-null  float64
 7   discount_percent    80000 non-null  int64
 8   final_price         80000 non-null  float64
 9   rating              80000 non-null  float64
 10  review_count        80000 non-null  int64
 11  stock_available     80000 non-null  int64
 12  units_sold          80000 non-null  int64
 13  listing_date        80000 non-null  datetime64[ns]
 14  delivery_days       80000 non-null  int64
 15  weight_g            80000 non-null  float64
 16  warranty_months     80000 non-null  int64
 17  color               80000 non-null  object
 18  size                80000 non-null  object
 19  return_policy_days  80000 non-null  int64
 20  is_returnable       80000 non-null  bool
 21  payment_modes       80000 non-null  object
 22  shipping_weight_g   80000 non-null  float64
 23  product_score       80000 non-null  float64
 24  seller_rating       80000 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(7), int64(7), object(9)
memory usage: 14.7+ MB

In [34]:
winter = df[
    df['order_date'].dt.month.isin([11, 12, 1])
]

In [35]:
winter.shape
winter.head()

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
5,6,2023-12-02,1777,Sports,385.17,30,3,Asia,Wallet,3.8,489,269.62,808.86
6,7,2022-01-21,4068,Books,15.78,0,5,Asia,UPI,1.6,415,15.78,78.90
11,12,2022-11-27,3637,Books,150.19,0,1,North America,Cash on Delivery,4.4,279,150.19,150.19
14,15,2023-01-08,1051,Beauty,66.65,10,2,North America,Debit Card,4.6,262,59.99,119.98
19,20,2022-11-05,3390,Fashion,428.24,30,3,Middle East,Wallet,1.2,331,299.77,899.31

In [36]:
winter['total_revenue'].sum()

np.float64(8230750.34)

In [37]:
winter['order_id'].nunique()

12480

In [38]:
winter['quantity_sold'].sum()

np.int64(37694)

In [39]:
winter['discount_percent'].mean()

np.float64(13.330929487179487)

In [40]:
winter.groupby(
    'product_category'
)['total_revenue'].sum().sort_values(
    ascending=False
)

product_category
Fashion           1418963.86
Electronics       1388570.56
Beauty            1382897.98
Home & Kitchen    1361239.66
Books             1342319.06
Sports            1336759.22
Name: total_revenue, dtype: float64

In [42]:
df['price'].mean()

np.float64(252.50726)

In [43]:
df2['price'].mean()

np.float64(30137.256453874998)

In [44]:
df['discount_percent'].mean()

np.float64(13.3407)

In [45]:
df2['discount_percent'].mean()

np.float64(21.350625)

In [46]:
df['rating'].mean()

np.float64(2.996316)

In [47]:
df2['rating'].mean()

np.float64(2.99967125)

In [48]:
df['review_count'].mean()

np.float64(249.32928)

In [49]:
df2['review_count'].mean()

np.float64(25102.249875)

In [50]:
df['quantity_sold'].mean()

np.float64(2.9994)

In [51]:

df2['units_sold'].mean()

np.float64(2507.515775)

In [52]:
df2['delivery_days'].mean()

np.float64(6.006325)

In [54]:
winter.shape

winter['total_revenue'].sum()

df['discount_percent'].mean()
df2['discount_percent'].mean()

df['rating'].mean()
df2['rating'].mean()

np.float64(2.99967125)

In [55]:
print("Winter Shape:", winter.shape)

print("Winter Revenue:", winter['total_revenue'].sum())

print("Amazon Discount:", df['discount_percent'].mean())
print("Flipkart Discount:", df2['discount_percent'].mean())

print("Amazon Rating:", df['rating'].mean())
print("Flipkart Rating:", df2['rating'].mean())

print("Flipkart Delivery:", df2['delivery_days'].mean())

Winter Shape: (12480, 13)
Winter Revenue: 8230750.34
Amazon Discount: 13.3407
Flipkart Discount: 21.350625
Amazon Rating: 2.996316
Flipkart Rating: 2.99967125
Flipkart Delivery: 6.006325